const {Router} = require("express")

const {saveUser,addNote,loginUser,getNote,deleteNotes,saveProtein,saveCarbo,saveFat,saveFiber,saveVitamin,saveMineral,saveBgwInitialPlan,saveAgwInitialPlan,saveIgwInitialPlan,saveBlwInitialPlan,saveIlwInitialPlan,saveAlwInitialPlan,saveBgwPostPlan,saveAgwPostPlan,saveIgwPostPlan,saveIlwPostPlan,saveAlwPostPlan,saveBlwPostPlan,getProtein,getCarbo,getFat,getFiber,getVitamin,getMineral,getBgwInitialPlan,getAgwInitialPlan,getIgwInitialPlan,getBlwInitialPlan,getIlwInitialPlan,getAlwInitialPlan,getBgwPostPlan,getAgwPostPlan,getIgwPostPlan,getIlwPostPlan,getAlwPostPlan,getBlwPostPlan } = require("../controllers/FitnessController")

const router = Router()

router.get('/getprotein',getProtein )
router.get('/getcarbo',getCarbo )
router.get('/getfat',getFat )
router.get('/getfiber',getFiber )
router.get('/getvitamin',getVitamin )
router.get('/getmineral',getMineral )
router.get('/getbgwinitialplan',getBgwInitialPlan )
router.get('/getagwinitialplan',getAgwInitialPlan )
router.get('/getigwinitialplan',getIgwInitialPlan )
router.get('/getblwinitialplan',getBlwInitialPlan )
router.get('/getilwinitialplan',getIlwInitialPlan )
router.get('/getalwinitialplan',getAlwInitialPlan )
router.get('/getbgwpostplan',getBgwPostPlan )
router.get('/getagwpostplan',getAgwPostPlan )
router.get('/getigwpostplan',getIgwPostPlan )
router.get('/getilwpostplan',getIlwPostPlan )
router.get('/getalwpostplan',getAlwPostPlan )
router.get('/getblwpostplan',getBlwPostPlan )

router.post('/saveprotein',saveProtein )
router.post('/savecarbo',saveCarbo )
router.post('/savefat',saveFat )
router.post('/savefiber',saveFiber )
router.post('/savevitamin',saveVitamin )
router.post('/savemineral',saveMineral )
router.post('/savebgwinitialplan',saveBgwInitialPlan )
router.post('/saveagwinitialplan',saveAgwInitialPlan )
router.post('/saveigwinitialplan',saveIgwInitialPlan )
router.post('/saveblwinitialplan',saveBlwInitialPlan )
router.post('/saveilwinitialplan',saveIlwInitialPlan )
router.post('/savealwinitialplan',saveAlwInitialPlan )
router.post('/savebgwpostplan',saveBgwPostPlan )
router.post('/saveagwpostplan',saveAgwPostPlan )
router.post('/saveigwpostplan',saveIgwPostPlan )
router.post('/saveilwpostplan',saveIlwPostPlan )
router.post('/savealwpostplan',saveAlwPostPlan )
router.post('/saveblwpostplan',saveBlwPostPlan )

router.post('/registeruser',saveUser)
router.post('/loginuser', loginUser)
router.get('/getuser',getNote)
router.post('/addnote', addNote)
router.delete('/deletenotes', deleteNotes)


module.exports = router;